export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAILED = 'GET_EMPLOYEES_FAILED';
export const ADD_TO_SELECTED_LIST = 'ADD_TO_SELECTED_LIST';
export const REMOVE_FROM_SELECTED_LIST = 'REMOVE_FROM_SELECTED_LIST';