export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export const ADD_TO_SELECTED_LIST = 'ADD_TO_SELECTED_LIST';
export const REMOVE_FROM_SELECTED_LIST = 'REMOVE_FROM_SELECTED_LIST';